
/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Nov 9 2021
 * Processor: STM32F103T6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include "stdio.h"
#include <usart.h>
#include <mef.h>
#include <delay.h>
#include <timer.h>
#include <usart.h>
#include "lcd.h"
#include "stdlib.h"

static volatile char prueba[]= "odio proteus";


void USART1_IRQHandler() { /* USART1 interrupt routine */
char c = USART1->DR; /* get received data */
 if (c != '\n'){
	   if (c == '\r'){  //SI ES CARACTER DE FIN DE CADENA
	            if (getTXindice_escritura() >0){
                    usart1_Write_Char_To_Buffer('\0');
                    } else {
                              usart1_Write_Char_To_Buffer('\r');
                              usart1_Write_Char_To_Buffer('\0');
                }
	            setLlegoMensaje(1); //llegoMensaje=1;
	            setTXindice_escritura(0);
	            } else {
		             usart1_Write_Char_To_Buffer(c); // AGREGO AL BUFFER
	            }
   }
 }

int main (void)
{
   timer_init();
   RCC->APB2ENR |= 0xFC | (1<<14) ; //enable clock for GPIO, USART1


   lcd_init();
   usart1_init();
   MEF_Init();
   delay_us(1000);
   usart1_sendStr("\r\n BIENVENIDO AL SISTEMA AUTOMATICO DE ILUMINACION \n Para conocer el porcentaje de iluminacion del cuarto ingrese CONOCER PORCENTAJE \r\n Para modificar el porcentaje de iluminacion ingrese CAMBIAR PORCENTAJE \r\n \0");
   while(1){
      //SI TIMER DE 1 SEGUNDO SE ACTIVO
        //ACTUALIZAR HORA
       if (timer_getFlag()){
	      MEF_Update();
	      timer_resetFlag();
	      }     
      }
}   

